# manually triggered workflow for reproducing a Checkstyle bug

name: Bug Reproduction

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Complete minimal Checkstyle config.xml content'
        default: |
          <module name="Checker">
            <module name="TreeWalker">
              <module name="ModifierOrder"/>
            </module>
          </module>
        required: true
        type: string
      java:
        description: 'Complete minimal Java file content'
        default: |
          public class Bug {
            final public someMethod() {
              // empty
            }
          }
        required: true
        type: string

jobs:
  reproduce:
    runs-on: ubuntu-latest

    steps:
    - name: Store Java file
      uses: 1arp/create-a-file-action@0.2
      with:
        path: 'input'
        file: 'Bug.java'
        content: ${{ inputs.java }}
    - name: Store config file
      uses: 1arp/create-a-file-action@0.2
      with:
        path: 'input'
        file: 'config.xml'
        content: ${{ inputs.config }}
    - name: Download Checkstyle
      run: curl https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.3/checkstyle-10.12.3-all.jar -o checkstyle-all.jar
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Checkstyle
      run: java -Duser.language=en -Duser.country=US -jar checkstyle-all.jar -c input/config.xml input/Bug.java
