# manually triggered workflow for reproducing a Checkstyle bug
# open issues:
# * Workflow input is single line only. Would need to have a small website to take the input and then trigger the REST API of the workflow.

name: Reproduce Checkstyle bug

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Complete minimal Checkstyle config.xml content'
        default: |
          <!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
          <module name="Checker">
            <module name="TreeWalker">
              <module name="ModifierOrder"/>
            </module>
          </module>
        required: true
        type: string
      java:
        description: 'Complete minimal Java file content'
        default: |
          public class Bug {
            final public someMethod() {
            }
          }
        required: true
        type: string

jobs:
  reproduce-bug:
    runs-on: ubuntu-latest

    steps:
    - name: Store Java file
      env:
        JAVA_FILE: ${{inputs.java}}
      shell: bash
      run: |
          echo "$JAVA_FILE" >> Bug.java
          cat Bug.java
    - name: Store config file
      env:
        CONFIG_FILE: ${{inputs.config}}
      shell: bash
      run: |
          echo "$CONFIG_FILE" >> config.xml
          cat config.xml
    - name: Download Checkstyle
      uses: robinraju/release-downloader@v1.8
      with:
        repository: checkstyle/checkstyle
        latest: true
        fileName: '*.jar'
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      # TODO: rename downloaded jar
    - name: Run Checkstyle
      run: java -Duser.language=en -Duser.country=US -jar checkstyle-10.12.3-all.jar -c config.xml Bug.java
